name: Test grammar

on:
  push:
    branches:
      - main
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    uses: tree-sitter-grammars/.github/.github/workflows/ci.yml@main
    with:
      # NOTE: change to true to also test the rust library:
      test-library: false
